# Generated by Django 5.2.6 on 2025-09-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('target_amount', models.FloatField()),
                ('amount_saved', models.FloatField()),
                ('interest_rate', models.FloatField()),
                ('target_date', models.DateField()),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
