# Generated by Django 5.2.6 on 2025-09-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
