# Generated by Django 5.2.6 on 2025-09-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_account_balance_alter_account_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
