# Generated by Django 5.2.6 on 2025-09-16 10:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_transaction_transaction_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='interest_rate',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
