# Generated by Django 5.2.6 on 2025-09-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_saving_account_delete_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saving_account',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
