# Generated by Django 5.2.6 on 2025-09-18 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_alter_goal_amount_saved_alter_goal_target_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='image',
        ),
    ]
